#spring:
#  application:
#    name: posbe
#  devtools:
#    add-properties: true
#  datasource:
#    url: jdbc:mysql://localhost:3306/demopos
#    username: root
#    password: 12345678
#    hikari:
#      minimum-idle: 5
#      maximum-pool-size: 10
#      idle-timeout: 30000
#      pool-name: HikariCP
#  servlet:
#    multipart:
#      enabled: true
#      max-file-size: 10MB
#      max-request-size: 10MB
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#    show-sql: true
#    hibernate:
#      ddl-auto: none
#server:
#  port: 8080
#
#springdoc:
#  api-docs:
#    enabled: true
#  swagger-ui:
#    enabled: true
#open-api:
#  service:
#    api-docs: demo
#    server: ${SWAGGER_ENDPOINT:http://localhost:8080}
#    title: Sample Service
#    version: 1.0
spring:
  application:
    name: posbe
  devtools:
    add-properties: true
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:demopos}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:12345678}
  servlet:
    multipart:
      enabled: true
      max-file-size: ${MAX_FILE_SIZE:10MB}
      max-request-size: ${MAX_REQUEST_SIZE:10MB}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: none

server:
  port: ${SERVER_PORT:8080}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
open-api:
  service:
    api-docs: demo
    server: ${SWAGGER_ENDPOINT}
    title: ${OPENAPI_TITLE}
    version: ${OPENAPI_VERSION}

